export { default as Main } from "./main/Main";
export { default as Asset1 } from "./assets/Asset1";
export { default as AccountSuccess } from "./assets/AccountSuccess";
export { default as AccountFail } from "./assets/AccountFail";
export { default as DepositSuccess } from "./assets/DepositSuccess";
export { default as DepositFail } from "./assets/DepositFail";
export { default as TradeMain } from "./trade/TradeMain";
export { default as TradeSuccess } from "./trade/TradeSuccess";
export { default as TradeFail } from "./trade/TradeFail";
